name: lovejourney
description: "Dating App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_colorpicker: ^1.1.0
  intl: any
  glass: any
  shared_preferences: any
  get_it: any
  image_picker: any
  flutter_guid: ^0.3.1
  fluttertoast: any
  responsive_sizer: any
  in_app_purchase: any
  flutter_rating_bar: any
  share_plus: any
  in_app_purchase_android: ^0.4.0
  in_app_purchase_platform_interface: ^1.4.0
  in_app_purchase_storekit: ^0.3.14
  package_info_plus:
  path_provider:
  flutter_svg: 
  flutter_dynamic_icon_plus: ^1.3.1
  in_app_review: ^2.0.10
  flutter_widget_from_html:
  morphable_shape: ^2.0.0
  change_app_package_name: ^1.5.0
  flutter_exit_app: ^1.1.4
  url_launcher: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.9.0
  build_runner: ^2.4.15
  #flutter pub run build_runner build 


flutter_gen:
  output: lib/gen/ 

  integrations:
    flutter_svg: true
  
  assets:
    enabled: true
    outputs:
      class_name: AssetsClass
      package_parameter_enabled: false

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/frames/
    - assets/backrounds/
    - assets/icons/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_bold.ttf
        - asset: assets/fonts/poppins_extrabold.ttf
        - asset: assets/fonts/poppins_extralight.ttf
        - asset: assets/fonts/poppins_light.ttf
        - asset: assets/fonts/poppins_medium.ttf
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_semibold.ttf
        - asset: assets/fonts/poppins_thin.ttf